=== 6merkl/qual-o-mat-data/schema/opinion.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Opinion list",
  "description": "All party opinions",
  "type": "array",
  "items": {
    "description": "Opinion",
    "type": "object",
    "properties": {
      "id": {
        "description": "Unique identifier",
        "type": "integer",
        "minimum": 0
      },
      "party": {
        "description": "ID representing the party",
        "type": "integer",
        "minimum": 0
      },
      "statement": {
        "description": "ID representing the statement",
        "type": "integer",
        "minimum": 0
      },
      "answer": {
        "description": "ID representing the party answer",
        "type": "integer",
        "minimum": 0
      },
      "comment": {
        "description": "ID representing the party comment",
        "type": [ "integer", "null" ],
        "minimum": 0
      }
    },
    "required": ["id", "party", "statement", "answer", "comment"]
  },
  "uniqueItems": true
}

=== 6merkl/qual-o-mat-data/data/2004/saarland/opinion.json
[
  {"id":0, "party":0, "statement":0, "answer":1, "comment":0},
  {"id":1, "party":0, "statement":1, "answer":0, "comment":1},
  {"id":2, "party":0, "statement":2, "answer":1, "comment":2},
  {"id":3, "party":0, "statement":3, "answer":0, "comment":3},
  {"id":4, "party":0, "statement":4, "answer":1, "comment":4},
  {"id":5, "party":0, "statement":5, "answer":0, "comment":5},
  {"id":6, "party":0, "statement":6, "answer":0, "comment":6},
  {"id":7, "party":0, "statement":7, "answer":1, "comment":7},
  {"id":8, "party":0, "statement":8, "answer":1, "comment":8},
  {"id":9, "party":0, "statement":9, "answer":0, "comment":9},
  {"id":10, "party":0, "statement":10, "answer":1, "comment":10},
  {"id":11, "party":0, "statement":11, "answer":0, "comment":11},
  {"id":12, "party":0, "statement":12, "answer":1, "comment":12},
  {"id":13, "party":0, "statement":13, "answer":1, "comment":13},
  {"id":14, "party":0, "statement":14, "answer":0, "comment":14},
  {"id":15, "party":0, "statement":15, "answer":0, "comment":15},
  {"id":16, "party":0, "statement":16, "answer":0, "comment":16},
  {"id":17, "party":0, "statement":17, "answer":1, "comment":17},
  {"id":18, "party":0, "statement":18, "answer":0, "comment":18},
  {"id":19, "party":0, "statement":19, "answer":1, "comment":19},
  {"id":20, "party":0, "statement":20, "answer":0, "comment":20},
  {"id":21, "party":0, "statement":21, "answer":1, "comment":21},
  {"id":22, "party":0, "statement":22, "answer":1, "comment":22},
  {"id":23, "party":1, "statement":0, "answer":1, "comment":23},
  {"id":24, "party":1, "statement":1, "answer":0, "comment":24},
  {"id":25, "party":1, "statement":2, "answer":1, "comment":25},
  {"id":26, "party":1, "statement":3, "answer":0, "comment":26},
  {"id":27, "party":1, "statement":4, "answer":1, "comment":27},
  {"id":28, "party":1, "statement":5, "answer":1, "comment":28},
  {"id":29, "party":1, "statement":6, "answer":2, "comment":29},
  {"id":30, "party":1, "statement":7, "answer":2, "comment":30},
  {"id":31, "party":1, "statement":8, "answer":1, "comment":31},
  {"id":32, "party":1, "statement":9, "answer":0, "comment":32},
  {"id":33, "party":1, "statement":10, "answer":1, "comment":33},
  {"id":34, "party":1, "statement":11, "answer":0, "comment":34},
  {"id":35, "party":1, "statement":12, "answer":1, "comment":35},
  {"id":36, "party":1, "statement":13, "answer":1, "comment":36},
  {"id":37, "party":1, "statement":14, "answer":0, "comment":37},
  {"id":38, "party":1, "statement":15, "answer":0, "comment":38},
  {"id":39, "party":1, "statement":16, "answer":0, "comment":39},
  {"id":40, "party":1, "statement":17, "answer":1, "comment":40},
  {"id":41, "party":1, "statement":18, "answer":1, "comment":41},
  {"id":42, "party":1, "statement":19, "answer":0, "comment":42},
  {"id":43, "party":1, "statement":20, "answer":1, "comment":43},
  {"id":44, "party":1, "statement":21, "answer":0, "comment":44},
  {"id":45, "party":1, "statement":22, "answer":0, "comment":45},
  {"id":46, "party":2, "statement":0, "answer":0, "comment":46},
  {"id":47, "party":2, "statement":1, "answer":1, "comment":47},
  {"id":48, "party":2, "statement":2, "answer":0, "comment":48},
  {"id":49, "party":2, "statement":3, "answer":1, "comment":49},
  {"id":50, "party":2, "statement":4, "answer":0, "comment":50},
  {"id":51, "party":2, "statement":5, "answer":1, "comment":51},
  {"id":52, "party":2, "statement":6, "answer":1, "comment":52},
  {"id":53, "party":2, "statement":7, "answer":1, "comment":53},
  {"id":54, "party":2, "statement":8, "answer":0, "comment":54},
  {"id":55, "party":2, "statement":9, "answer":1, "comment":55},
  {"id":56, "party":2, "statement":10, "answer":0, "comment":56},
  {"id":57, "party":2, "statement":11, "answer":1, "comment":57},
  {"id":58, "party":2, "statement":12, "answer":0, "comment":58},
  {"id":59, "party":2, "statement":13, "answer":0, "comment":59},
  {"id":60, "party":2, "statement":14, "answer":1, "comment":60},
  {"id":61, "party":2, "statement":15, "answer":1, "comment":61},
  {"id":62, "party":2, "statement":16, "answer":1, "comment":62},
  {"id":63, "party":2, "statement":17, "answer":0, "comment":63},
  {"id":64, "party":2, "statement":18, "answer":1, "comment":64},
  {"id":65, "party":2, "statement":19, "answer":0, "comment":65},
  {"id":66, "party":2, "statement":20, "answer":0, "comment":66},
  {"id":67, "party":2, "statement":21, "answer":1, "comment":67},
  {"id":68, "party":2, "statement":22, "answer":0, "comment":68},
  {"id":69, "party":3, "statement":0, "answer":0, "comment":69},
  {"id":70, "party":3, "statement":1, "answer":1, "comment":70},
  {"id":71, "party":3, "statement":2, "answer":0, "comment":71},
  {"id":72, "party":3, "statement":3, "answer":1, "comment":72},
  {"id":73, "party":3, "statement":4, "answer":1, "comment":73},
  {"id":74, "party":3, "statement":5, "answer":1, "comment":74},
  {"id":75, "party":3, "statement":6, "answer":1, "comment":75},
  {"id":76, "party":3, "statement":7, "answer":0, "comment":76},
  {"id":77, "party":3, "statement":8, "answer":2, "comment":77},
  {"id":78, "party":3, "statement":9, "answer":1, "comment":78},
  {"id":79, "party":3, "statement":10, "answer":0, "comment":79},
  {"id":80, "party":3, "statement":11, "answer":1, "comment":80},
  {"id":81, "party":3, "statement":12, "answer":0, "comment":81},
  {"id":82, "party":3, "statement":13, "answer":1, "comment":82},
  {"id":83, "party":3, "statement":14, "answer":1, "comment":83},
  {"id":84, "party":3, "statement":15, "answer":0, "comment":84},
  {"id":85, "party":3, "statement":16, "answer":2, "comment":85},
  {"id":86, "party":3, "statement":17, "answer":0, "comment":86},
  {"id":87, "party":3, "statement":18, "answer":1, "comment":87},
  {"id":88, "party":3, "statement":19, "answer":0, "comment":88},
  {"id":89, "party":3, "statement":20, "answer":0, "comment":89},
  {"id":90, "party":3, "statement":21, "answer":1, "comment":90},
  {"id":91, "party":3, "statement":22, "answer":1, "comment":91},
  {"id":92, "party":4, "statement":0, "answer":1, "comment":92},
  {"id":93, "party":4, "statement":1, "answer":2, "comment":93},
  {"id":94, "party":4, "statement":2, "answer":0, "comment":94},
  {"id":95, "party":4, "statement":3, "answer":1, "comment":95},
  {"id":96, "party":4, "statement":4, "answer":2, "comment":96},
  {"id":97, "party":4, "statement":5, "answer":1, "comment":97},
  {"id":98, "party":4, "statement":6, "answer":1, "comment":98},
  {"id":99, "party":4, "statement":7, "answer":0, "comment":99},
  {"id":100, "party":4, "statement":8, "answer":0, "comment":100},
  {"id":101, "party":4, "statement":9, "answer":0, "comment":101},
  {"id":102, "party":4, "statement":10, "answer":0, "comment":102},
  {"id":103, "party":4, "statement":11, "answer":1, "comment":103},
  {"id":104, "party":4, "statement":12, "answer":0, "comment":104},
  {"id":105, "party":4, "statement":13, "answer":1, "comment":105},
  {"id":106, "party":4, "statement":14, "answer":1, "comment":106},
  {"id":107, "party":4, "statement":15, "answer":2, "comment":107},
  {"id":108, "party":4, "statement":16, "answer":1, "comment":108},
  {"id":109, "party":4, "statement":17, "answer":0, "comment":109},
  {"id":110, "party":4, "statement":18, "answer":1, "comment":110},
  {"id":111, "party":4, "statement":19, "answer":0, "comment":111},
  {"id":112, "party":4, "statement":20, "answer":0, "comment":112},
  {"id":113, "party":4, "statement":21, "answer":1, "comment":113},
  {"id":114, "party":4, "statement":22, "answer":2, "comment":114}
]
